// ── Bilingual hardcoded strings for the receipt PDF template ────────────────

export const TEXTS = {
  companyNameEn: "LMC Management Consultancy Ltd.",
  companyNameZh: "德智管理顧問有限公司",
  receiptTitleEn: "OFFICIAL RECEIPT",
  receiptTitleZh: "正式收據",
  receiptNoLabel: "Receipt No. / 收據編號",
  dateLabel: "Date / 日期",
  registrantSection: "Registrant / 學員資料",
  nameEnLabel: "Name / 姓名 (EN)",
  nameZhLabel: "Name / 姓名 (ZH)",
  courseSection: "Course Details / 課程詳情",
  tableDescription: "Description / 項目",
  tableIaRef: "IA Ref / 參考編號",
  tableCpd: "CPD / 時數",
  tableAmount: "Amount / 金額",
  totalPrefix: "Total / 合計: HKD ",
  paymentSection: "Payment / 付款資料",
  methodLabel: "Method / 付款方式",
  statusLabel: "Status / 狀態",
  statusVerified: "Verified / 已核實",
  stampTitle: "LMC Management Consultancy Ltd.",
  stampSubtitle: "德智管理顧問有限公司",
  stampAuthorised: "Authorised Receipt / 授權收據",
  footerDisclaimer: "This is a computer-generated receipt. No signature required. / 此為電腦生成收據，無須簽署。",
  footerAddress: "LMC Management Consultancy Ltd. | Unit 1011-15, 10/F., Tower B, New Mandarin Plaza, Tsim Sha Tsui East, Kowloon, Hong Kong",
  dash: "—",
} as const;